services:
  reddit-classifier:
    build: .
    container_name: reddit_nlp_classifier
    environment:
      - PRAW_CLIENT_ID=${PRAW_CLIENT_ID}
      - PRAW_CLIENT_SECRET=${PRAW_CLIENT_SECRET}
      - PRAW_USER_AGENT=${PRAW_USER_AGENT}
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
      - ./results:/app/results
      - ./data:/app/data
      - ./models:/app/models
    command: python interactive_demo.py
    stdin_open: true
    tty: true

  demo-quick:
    build: .
    container_name: redditproject-demo-quick-1
    environment:
      - PRAW_CLIENT_ID=${PRAW_CLIENT_ID}
      - PRAW_CLIENT_SECRET=${PRAW_CLIENT_SECRET}
      - PRAW_USER_AGENT=${PRAW_USER_AGENT}
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
      - ./results:/app/results
      - ./data:/app/data
      - ./models:/app/models
    command: python interactive_demo.py --quick-demo

  summary:
    build: .
    container_name: redditproject-summary-1
    environment:
      - PRAW_CLIENT_ID=${PRAW_CLIENT_ID}
      - PRAW_CLIENT_SECRET=${PRAW_CLIENT_SECRET}
      - PRAW_USER_AGENT=${PRAW_USER_AGENT}
      - PYTHONPATH=/app
    volumes:
      - ./src:/app/src
      - ./results:/app/results
      - ./data:/app/data
      - ./models:/app/models
    command: python project_summary.py --save-report